name: 'Go Badge Generator'
description: 'Replaces comments in readme with badges based on input.'
inputs:
  readme-path:
    description: 'path to the readme file for update'
    required: false
    default: "README.md"
  coverage:
    description: 'Code coverage percentage as a floating point number (without % symbol)'
    required: false
    default: "-1"
  report-card:
    description: 'Whether or not to run go report card and include the output'
    required: false
    default: "true"
  version:
    description: 'String representation of the current code version'
    required: false
    default: "-1"
  commit-msg:
    description: 'message to include in the readme commit'
    required: false
    default: 'go-badges update'
outputs:
  readme: # id of output
    description: 'The updated readme'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.readme-path }}
    - ${{ inputs.coverage }}
    - ${{ inputs.report-card }}
    - ${{ inputs.version }}
    - ${{ inputs.commit-msg }}
