name: 'Go Badge Generator'
description: 'Replaces comments in readme with badges based on input.'
inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  readme-path:
    description: 'path to the readme file for update'
    required: false
    default: "README.md"
  coverage:
    description: 'Code coverage percentage as a floating point number (without % symbol)'
    required: false
    default: "-1"
  report-card:
    description: 'Whether or not to run go report card and include the output'
    required: false
    default: "true"
  version:
    description: 'String representation of the current code version'
    required: false
    default: "-1"
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.readme-path }}
    - ${{ inputs.coverage }}
    - ${{ inputs.report-card }}
    - ${{ inputs.version }}