on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        id: version
        env:
          RELEASE_BRANCHES: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "none"
      - id: badges
        uses: jacobkring/go-badges@v1.9.5
        with:
          version: ${{ steps.version.outputs.tag }}
          commit-msg: 'go-badges update'