on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        id: version
        env:
          RELEASE_BRANCHES: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - id: badges
        uses: jacobkring/go-badges@v1.0.0-rc17
        with:
          version: ${{ steps.version.outputs.tag }}
      # Use the output from the `hello` step
      - name: Get the updated readme
        run: echo "The readme is ${{ steps.hello.outputs.readme }}"
