on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and Bump Version
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Go Report Card
        id: reportCard
        run: |
          go get -u github.com/client9/misspell/cmd/misspell
          git clone https://github.com/gojp/goreportcard.git
          cd goreportcard
          make install
          go install ./cmd/goreportcard-cli
          cd .. && rm -rf goreportcard
          goreportcard-cli -t 85.0
          reportCard=`goreportcard-cli`
          echo $reportCard
          echo "::set-output name=reportCard::${reportCard}"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        id: version
        env:
          RELEASE_BRANCHES: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "none"

      - id: badges
        uses: jacobkring/go-badges@v1.9.14
        with:
          version: ${{ steps.version.outputs.tag }}
          report-card: ${{ steps.reportCard.outputs.reportCard }}