on: [push]
env:
  COVERAGE_REQUIREMENT: 80
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and Bump Version
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Go Report Card
        id: goreportcard
        run: |
          go get -u github.com/client9/misspell/cmd/misspell
          git clone https://github.com/gojp/goreportcard.git
          cd goreportcard
          make install
          go install ./cmd/goreportcard-cli
          cd .. && rm -rf goreportcard
          output=`goreportcard-cli -t 85.0`
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=reportCard::${output}"

      - name: 'Run Tests'
        run: |
          go test ./... -p=1 -covermode=count -coverprofile=coverage.out

      - name: Check Coverage
        id: coverage
        run: |
          coverage=`go tool cover -func coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}'`
          echo "Coverage: ${coverage}%"
          echo "::set-output name=coverage::${coverage}"
          if (( $(echo "$coverage < $COVERAGE_REQUIREMENT" |bc -l) )); then
            echo "Not enough code coverage\!"
            exit 1
          fi

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        id: version
        env:
          RELEASE_BRANCHES: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "none"

      - id: badges
        uses: jacobkring/go-badges@v1.10.22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: v1.10.22
          report-card: ${{ steps.goreportcard.outputs.reportCard }}
          coverage: ${{ steps.coverage.outputs.coverage }}
          IS_GO_BADGES: "true"