on: [push]
env:
  COVERAGE_REQUIREMENT: 80
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and Bump Version
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Go Report Card
        id: goreportcard
        uses: jacobkring/actions-goreportcard@v0.0.5
        with:
          threshold: "-t 80"

      - name: 'Run Tests'
        run: |
          go test ./... -p=1 -covermode=count -coverprofile=coverage.out

      - name: Check Coverage
        id: coverage
        run: |
          coverage=`go tool cover -func coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}'`
          echo "Coverage: ${coverage}%"
          echo "::set-output name=coverage::${coverage}"
          if (( $(echo "$coverage < $COVERAGE_REQUIREMENT" |bc -l) )); then
            echo "Not enough code coverage\!"
            exit 1
          fi

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        id: version
        env:
          RELEASE_BRANCHES: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "none"

      - id: badges
        uses: jacobkring/go-badges@v1.10.34
        with:
          version: v1.10.34
          report-card: ${{ steps.goreportcard.outputs.summary }}
          coverage: ${{ steps.coverage.outputs.coverage }}
          IS_GO_BADGES: "true"

      - name: Commit README.md
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          cat README.md
          git add README.md
          git commit -m "go-badges update"
          git push